### PR TITLE
Improved character

### PR DESCRIPTION
**Pull request by The210**
Feel free to focus mainly on the following scripts:

[PlayerCollissions](https://github.com/One-Drill/RhythmBoi/compare/ImprovedCharacter?expand=1#diff-f1d9b376659c6f0f8ec7995654a13095)
[CharacterController](https://github.com/One-Drill/RhythmBoi/compare/ImprovedCharacter?expand=1#diff-9138b07c559825cfbd615208d1fe5f10)

Worked on a new system of collisions, on top of the ones we previously had. This should allow, for the most part, the use of:

- Stairs
- Ramps
- up-down moving platforms.
- Horizontally pushing blocks.

Also worked on fixing a bug for gradual movement of the player when using a controller, and using Time.deltaTime for his movement, so that it is not framerate dependant. As a side effect, most values for player movement are now "off", making the level not balanced, which is something we should work on later.

### CODE REVIEW

**Review by wendrul — APPROVED** [review]
lgtm!

**Comment by YujeK** [comment]
Y

**Comment by YujeK** [comment]
Y

**Comment by YujeK** [comment]
Y

**Review by YujeK — APPROVED** [review]
Nice i´ve read everything, amazing code right there.

**Review by Smerelo — APPROVED** [review]

**Pull request merged**
